# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('artist_name', models.CharField(max_length=200)),
                ('album_name', models.CharField(max_length=200)),
                ('mp3_url', models.CharField(max_length=200)),
                ('netease_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicbox.Playlist'),
        ),
    ]
